version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    #ports:
    #  - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
